# Numpy 函数库

numpy.random 随机生成

numpy.mat 变成矩阵

In [21]:
import numpy as np
np.random.rand(4,4)
np.mat(np.random.rand(4,4))

matrix([[0.89721671, 0.10917063, 0.51099112, 0.36572358],
        [0.01312145, 0.30348989, 0.99746745, 0.77184552],
        [0.21869038, 0.80043406, 0.90262903, 0.90925217],
        [0.75684557, 0.81944597, 0.22935939, 0.12371664]])

In [19]:
MatA = np.mat(np.random.rand(2,4))
MatB = np.mat(np.random.rand(4,2))
print("-"*40)
print(MatA*MatB)
print("-"*40)
print(MatA)
print("-"*40)
print(MatB)

----------------------------------------
[[1.19643944 2.14143489]
 [0.40830374 0.50418034]]
----------------------------------------
[[0.74015772 0.98513418 0.74656633 0.97611477]
 [0.20607236 0.06047789 0.53765692 0.11138357]]
----------------------------------------
[[0.52175677 0.50234898]
 [0.2115024  0.95346236]
 [0.48470006 0.54865583]
 [0.24591181 0.43101599]]


## 求逆矩阵

In [22]:
MatA.I

matrix([[ 0.20419949,  0.1685664 ],
        [ 0.56252073, -0.99477497],
        [-0.24251074,  2.05061736],
        [ 0.48739363, -0.69223497]])

### np.eye(n) 是一个n-dimension 的单位矩阵

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
MatC = np.mat(np.rand)