#### Numpy 函数库

numpy.random
numpy.mat 

In [11]:
import numpy as np
np.random.rand(4,4)
np.mat(np.random.rand(4,4))

matrix([[-4.87925388,  3.73692528, -1.27206604,  6.84158353],
        [ 5.10858526, -3.36746843,  2.39505375, -9.50211608],
        [ 0.64614445, -2.21007415,  0.91679608,  4.10379923],
        [-0.68042919,  2.51209562, -2.06166687,  0.44490874]])

In [19]:
MatA = np.mat(np.random.rand(2,4))
MatB = np.mat(np.random.rand(4,2))
print("-"*40)
print(MatA*MatB)
print("-"*40)
print(MatA)
print("-"*40)
print(MatB)

----------------------------------------
[[1.19643944 2.14143489]
 [0.40830374 0.50418034]]
----------------------------------------
[[0.74015772 0.98513418 0.74656633 0.97611477]
 [0.20607236 0.06047789 0.53765692 0.11138357]]
----------------------------------------
[[0.52175677 0.50234898]
 [0.2115024  0.95346236]
 [0.48470006 0.54865583]
 [0.24591181 0.43101599]]
