# Numpy
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.
<a href = "">reference link</a>

In [34]:
import numpy as np
a = np.array([1,23,3,4,5,7])
## 一维数组
print(a)

b = np.array([[12,2,3],[2,3,4]])
print(b)

[ 1 23  3  4  5  7]
[[12  2  3]
 [ 2  3  4]]


In [7]:
# 查看numpy的版本
def check_version(version):
    print(version)
    
check_version(np.__version__)

1.21.5


In [30]:
# ndarray: N-Dimensional array(ndarray) in Numpy 
# Array in Numpy is a table of elements (usually numbers), 
# all of the same type, indexed by a tuple of positive integers. 
# In Numpy, number of dimensions of the array is called rank of the array.
# A tuple of integers giving the size of the array along each dimension is known as shape of the array. 
# An array class in Numpy is called as ndarray

arr = np.ndarray((2,2))
print(arr)
print("the type of arr:" + str(type(arr)))

brr = np.ones((3,3))
print(brr)

[[0. 0.]
 [0. 0.]]
the type of arr:<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
